version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: athena_db
      POSTGRES_USER: athena_user
      POSTGRES_PASSWORD: athena_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.15
    environment:
      NEO4J_AUTH: neo4j/athena_password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://athena_user:athena_password@postgres:5432/athena_db
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=athena_password
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your_secret_key_here_change_in_production
      - JWT_SECRET=your_jwt_secret_here_change_in_production
      - LISTEN_NOTES_API_KEY=""
      - ASSEMBLYAI_API_KEY=""
      - SPORTRADAR_API_KEY=""
      - NEWS_API_KEY=""
      - SPORTSDATA_API_KEY=""
      - VECTOR_DB_PATH=./backend/chroma_db
      - PODCAST_BATCH_SIZE=5
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - neo4j
      - redis
    volumes:
      - ./backend:/app
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  neo4j_data:
  redis_data:
